# my-agent-web — the interactive web GUI profile with configurable providers.
# Generated by bin/setup.sh from the agent-with-dsh framework templates.

# 1) Multi-provider LLM routes through the pi-ai adapter (same as headless).
- id: llm-pi-ai
  config:
    providers:
      deepseek:
        apiKeyEnv: DEEPSEEK_API_KEY
        displayName: DeepSeek
      openai:
        apiKeyEnv: OPENAI_API_KEY
        displayName: OpenAI
      anthropic:
        apiKeyEnv: ANTHROPIC_API_KEY
        displayName: Anthropic (Claude)
      openrouter:
        apiKeyEnv: OPENROUTER_API_KEY
        displayName: OpenRouter
      ollama:
        displayName: Ollama (local)
        api: openai-completions
        baseURL: http://localhost:11434/v1
        models:
          - id: llama3.2
            name: Llama 3.2
            contextWindow: 128000
          - id: qwen2.5
            name: Qwen 2.5
            contextWindow: 32768
          - id: deepseek-r1
            name: DeepSeek R1 (distill)
            contextWindow: 65536

# 2) Default model route.
- id: agent-default-model
  config:
    provider: deepseek
    model: deepseek-v4-flash

# 3) Default persona (the UI can override per session).
- id: system-prompt
  config:
    persona: |
      You are my-agent, a helpful assistant running inside the agent-with-dsh
      framework. Be concise and factual.

# 4) Your own plugins.
- insert:
    - id: my-agent-tools
      name: '__REPO__/examples/dsh-tools-plugin.ts'
