# my-agent-headless — one-shot CLI agent with configurable providers.
# Generated by bin/setup.sh from the agent-with-dsh framework templates
# (__REPO__ is replaced with this repository's absolute path).

# 1) Multi-provider LLM routes through the pi-ai adapter. Set the matching
#    env vars (or ~/.dsh/settings.yaml sections) with your API keys:
#    DEEPSEEK_API_KEY, OPENAI_API_KEY, ANTHROPIC_API_KEY, OPENROUTER_API_KEY.
#    Ollama is a keyless local server.
- id: llm-pi-ai
  config:
    providers:
      deepseek:
        apiKeyEnv: DEEPSEEK_API_KEY
        displayName: DeepSeek
      openai:
        apiKeyEnv: OPENAI_API_KEY
        displayName: OpenAI
      anthropic:
        apiKeyEnv: ANTHROPIC_API_KEY
        displayName: Anthropic (Claude)
      openrouter:
        apiKeyEnv: OPENROUTER_API_KEY
        displayName: OpenRouter
      ollama:
        displayName: Ollama (local)
        api: openai-completions
        baseURL: http://localhost:11434/v1
        models:
          - id: llama3.2
            name: Llama 3.2
            contextWindow: 128000
          - id: qwen2.5
            name: Qwen 2.5
            contextWindow: 32768
          - id: deepseek-r1
            name: DeepSeek R1 (distill)
            contextWindow: 65536

# 2) Default model route. Change provider/model here, or live via the
#    ~/.dsh/settings.yaml `llm-pi-ai:` section (the web Models page writes it).
- id: agent-default-model
  config:
    provider: deepseek
    model: deepseek-v4-flash

# 3) Persona of the one-shot agent.
- id: system-prompt
  config:
    persona: |
      You are my-agent, a coding assistant powered by the {{model}} model,
      running inside the agent-with-dsh framework. Verify your work by running
      code or tests. Keep answers brief and factual.

# 4) Your own plugins (tools, hooks). Add more `- insert:` lists here, or edit
#    examples/dsh-tools-plugin.ts. The absolute path is substituted by setup.sh.
- insert:
    - id: my-agent-tools
      name: '__REPO__/examples/dsh-tools-plugin.ts'
